// Generated by gencpp from file me212bot/mobile_step.msg
// DO NOT EDIT!


#ifndef ME212BOT_MESSAGE_MOBILE_STEP_H
#define ME212BOT_MESSAGE_MOBILE_STEP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me212bot
{
template <class ContainerAllocator>
struct mobile_step_
{
  typedef mobile_step_<ContainerAllocator> Type;

  mobile_step_()
    : step(0)  {
    }
  mobile_step_(const ContainerAllocator& _alloc)
    : step(0)  {
  (void)_alloc;
    }



   typedef int32_t _step_type;
  _step_type step;




  typedef boost::shared_ptr< ::me212bot::mobile_step_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me212bot::mobile_step_<ContainerAllocator> const> ConstPtr;

}; // struct mobile_step_

typedef ::me212bot::mobile_step_<std::allocator<void> > mobile_step;

typedef boost::shared_ptr< ::me212bot::mobile_step > mobile_stepPtr;
typedef boost::shared_ptr< ::me212bot::mobile_step const> mobile_stepConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me212bot::mobile_step_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me212bot::mobile_step_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me212bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me212bot': ['/home/robot/mobile/catkin_ws/src/me212bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me212bot::mobile_step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me212bot::mobile_step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212bot::mobile_step_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212bot::mobile_step_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212bot::mobile_step_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212bot::mobile_step_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me212bot::mobile_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99174260c0c07917ce2b7a46302ab7a8";
  }

  static const char* value(const ::me212bot::mobile_step_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99174260c0c07917ULL;
  static const uint64_t static_value2 = 0xce2b7a46302ab7a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::me212bot::mobile_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me212bot/mobile_step";
  }

  static const char* value(const ::me212bot::mobile_step_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me212bot::mobile_step_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 step\n\
";
  }

  static const char* value(const ::me212bot::mobile_step_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me212bot::mobile_step_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct mobile_step_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me212bot::mobile_step_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me212bot::mobile_step_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<int32_t>::stream(s, indent + "  ", v.step);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME212BOT_MESSAGE_MOBILE_STEP_H
